# https://aka.ms/yaml

jobs:
- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.15'
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Checkout Submodules'
  - bash: |
      python3 -m pip install pyyaml
      python3 ./utils/build_script_generator.py ./.github/workflows/build_deps.yml
      echo "  + Build scripts successfully generated"
    displayName: Generate build scripts
  - script: TERM="" bash ./build-script-macos-01.sh
    displayName: 'Build dependencies'
  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './macos'
      artifactName: osx-deps
